### ISSUE TITLE
Segfault when creating database

### ISSUE THREAD

**Issue by gacharya255** [Terark/terarkdb#1]
We tried running RocksDB with Terark plugin according to the instructions on "trying out TerarkDB with minimal effort, but encountered three roadblocks.

First, compiling the forked RocksDB using `make shared_lib` failed with the error:
```
tools/ldb_cmd.cc:35:44: fatal error: table/terark_zip_weak_function.h: No such file or directory
```

We looked around for this file and eventually found it in one of the repo. We then clone the repo `terark-zip-rocksdb` to the right place and manage to compile RocksDB.

Second, when we try running with `LD_PRELOAD` set, running led to the error
```
symbol lookup error: /home/ganesh/installs/terark-zip-rocksdb-trial-Linux-x86_64-g++-5.4-bmi2-1/lib/libterark-zip-rocksdb-trial-r.so: undefined symbol: _ZN7rocksdb5Arena13kMinBlockSizeE
```

To fix this, we used the following instead:
```
export LD_PRELOAD=librocksdb.so:libterark-zip-rocksdb-trial-r.so:libterark-core-r.so:libterark-fsa-r.so:libterark-zbs-r.so
```

Third, when we try to run, we encountered a segfault. RocksDB is invoked via cgo. We're not sure what's happening here. Here is a link to our Go RocksDB wrapper: https://github.com/dgraph-io/dgraph/tree/master/rdb. Also, we were using terark-zip-rocksdb-trial-Linux-x86_64-g++-5.4-bmi2-1 and the master branch from the forked rocksdb. Here is the segfault when we were opening a new RocksDB store:

```
2017-04-06 23:02:56 INFO: NewTerarkZipTableFactory()
2017-04-06 23:02:56 INFO: TerarkZipConfigFromEnv(dbo, cfo) successed
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd pc=0x7f3d5f193699]

runtime stack:
runtime.throw(0x8040d2, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x730ed0, 0xc420057d90, 0xc42000e0c8)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420057d60 sp=0xc420057d20
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_open(0x29a31b0, 0x2995410, 0xc42000e0c8, 0x0)
	github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:542 +0x4e fp=0xc420057d90 sp=0xc420057d60
github.com/dgraph-io/dgraph/rdb.OpenDb.func2(0x29a31b0, 0x2995410, 0xc42000e0c8, 0x299db01)
	/home/ganesh/go/src/github.com/dgraph-io/dgraph/rdb/db.go:50 +0x106 fp=0xc420057dd8 sp=0xc420057d90
github.com/dgraph-io/dgraph/rdb.OpenDb(0xc420015c90, 0xc420019b90, 0x25, 0x0, 0x0, 0x0)
```

**Comment by rockeet** [comment]
You are using `trail` version of `libterark-zip-rocksdb`,  `0.1%` of data will be silently overwrite in `trial` version. This is OK for simple `KeyValue` benchmark, but it is undifined behavior when value are asumed to be some strict format(such as protobuf serailization in dgraph).

We can give you a full version.

**Comment by gacharya255** [comment]
Got it. Thanks @rockeet
