### ISSUE TITLE
when executing db_bench, it shows "libterark_zip_rocksdb.so is not loaded"

### ISSUE THREAD

**Issue by foudrer** [Terark/terarkdb#3]
when executing db_bench, it shows "libterark_zip_rocksdb.so is not loaded", how to solve the problem??
I have already  set these environment variables. Thank you!

**Comment by mm304321141** [comment]
env LD_PRELOAD=/path/to/so

**Comment by rockeet** [comment]
see: [Try-TerarkDB-With-Minimal-Effort](https://github.com/Terark/terarkdb/wiki/Try-TerarkDB-With-Minimal-Effort)
notes: you must download [precompiled terark-zip-rocksdb](http://www.terark.com/download/terarkdb/latest) first

**Comment by foudrer** [comment]
export LD_LIBRARY_PATH=/home/github/terarkdb/terark-zip-rocksdb/terark-zip-rocksdb-Linux-x86_64-g++-4.8-bmi2-1/lib:/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64:$LD_LIBRARY_PATH

env LD_PRELOAD=/home/github/terarkdb/terark-zip-rocksdb-Linux-x86_64-g++-4.8-bmi2-1/lib/libterark-zip-rocksdb-r.so \
        TerarkZipTable_localTempDir=/store5/terark \
        TerarkZipTable_indexNestLevel=2 \
        TerarkZipTable_indexCacheRatio=0.005 \
        TerarkZipTable_smallTaskMemory=1G \
        TerarkZipTable_softZipWorkingMemLimit=16G \
        TerarkZipTable_hardZipWorkingMemLimit=32G

The above content is in ~/.bash_profile, and I also execute "source ~/.bash_profile". However, when I run "db_bench", it still show
 "use_terarkzip_table, set mmap_read = true NewTerarkZipTableFactory is 0
ERROR: use_terarkzip_table, but libterark_zip_rocksdb.so is not loaded
"
and the precompiled terark-zip-rocksdb is in the directory "terark-zip-rocksdb"
"3rdparty         cpu_has_bmi2.sh  LICENSE   README.md  terark-zip-rocksdb-Linux-x86_64-g++-4.8-bmi2-1      tools cpu_features.sh  gen_env_conf.sh  Makefile  src        terark-zip-rocksdb-Linux-x86_64-g++-4.8-bmi2-1.tgz  vs2015
"

**Comment by rockeet** [comment]
It seems you are not familiar with shell scripting and didn't follow the instructions in [Try-TerarkDB-With-Minimal-Effort](https://github.com/Terark/terarkdb/wiki/Try-TerarkDB-With-Minimal-Effort).

Only `export LD_LIBRARY_PATH=...` can be in `~/.bash_profile`.

`env EnvName=EnvValue program args...` means run `program` with `EnvName=EnvValue`  set.

your `env ...` in `~/.bash_profile` will do nothing, you should follow our instrutions:
```bash
# If you have installed files in `terark-zip-rocksdb-XXX/lib` into
# system lib path(such as /usr/lib64), `LD_LIBRARY_PATH` is not needed.
export LD_LIBRARY_PATH=terark-zip-rocksdb-XXX/lib:$LD_LIBRARY_PATH

env LD_PRELOAD=libterark-zip-rocksdb-r.so \
    TerarkZipTable_localTempDir=/path/to/some/temp/dir \
    TerarkZipTable_indexNestLevel=2 \
    TerarkZipTable_indexCacheRatio=0.005 \
    TerarkZipTable_smallTaskMemory=1G \
    TerarkZipTable_softZipWorkingMemLimit=16G \
    TerarkZipTable_hardZipWorkingMemLimit=32G \
    app_exe_file app_args...
```
here `app_exe_file app_args...` is `db_bench args ...`.

Note: Although `db_bench` works, `db_bench` running benchmarks on generated random data, this is less useful than running bench on real data.

**Comment by foudrer** [comment]
Thank you very much, I will try it again

**Comment by foudrer** [comment]
Thank you very much! I will try it again!
