### ISSUE TITLE
When the value size is small, it can not trigger "ZipInputData/WriteZipData" 

### ISSUE THREAD

**Issue by foudrer** [Terark/terarkdb#4]
Hi, rockeet,
        I just try terarkdb with db_bench, and its performance is amazing, and I also have a problem during the experiment.  When the value size is larger than 64 bytes (the number of records is 171585163), I can see the terark-zip-rocksdb info, just like "start step...: ZipInputData", hence the terark-zip-rocksdb works well. However, the value size is set to be smaller than 64 bytes, for example 32 bytes (the number of records is 171585163), there is no terark-zip-rocksdb info. Are the data volume too small or other problems?
       Thank you, and looking forward to your reply!
foudrer

**Comment by mm304321141** [comment]
https://github.com/Terark/terark-zip-rocksdb/blob/beaac4e82d815fd997549fba938787bf183e312c/src/table/terark_zip_table.h#L78

**Comment by mm304321141** [comment]
https://github.com/Terark/terark-zip-rocksdb/blob/master/src/table/terark_zip_table.h#L90

**Comment by mm304321141** [comment]
```
use dictZip for value when average value length >= minDictZipValueSize
otherwise do not use dictZip
```
when agv value length is very short , we should disable compress .
e.g. short values needn't entropy encoding ...

**Comment by foudrer** [comment]
if the value is too short, for example, plate number, does terarkdb work well when it store plate number?

**Comment by rockeet** [comment]
it always works, just do not use PA-Zip compression for value when value is short.
the keys will always be compressed by CO-Index

**Comment by foudrer** [comment]
Thank you for your reply!
